theme: jekyll-theme-slate
title: Smart Contract Vulnerability Detection
description: Ethereum Smart Contracts Vulnerability Detection using Deep Neural Network and Transfer Learning
markdown: kramdown
repository: sss-wue/smarter-contracts 
github:
  is_project_page: true
